# permissions for end users to view basicresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basicresource-viewer-role
rules:
- apiGroups:
  - basic.example.com
  resources:
  - basicresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - basic.example.com
  resources:
  - basicresources/status
  verbs:
  - get
