# permissions for end users to edit basicresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basicresource-editor-role
rules:
- apiGroups:
  - basic.example.com
  resources:
  - basicresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - basic.example.com
  resources:
  - basicresources/status
  verbs:
  - get
